h5p/h5p-interactive-book

src/scripts/pagecontent.js
src/scripts/sidebar.js
src/styles/_navigationbar.scss
src/styles/main.scss

Adjust menu height when more than 20 pages in the book

HFP-2600 - handle big menus

---

package-lock.json
package.json
src/scripts/app.js
src/scripts/statusbar.js

Scroll to the top of the content when using the buttons for navigation.

HFP-2598 - scroll when using buttons or menu for navigation

---

src/scripts/app.js
src/scripts/pagecontent.js

If empty pages are found they are removed from the config

HFP-2597 - remove empty pages

---

src/scripts/app.js

Set half-circle on chapters with started tasks.

HFP-2595 - half-circles on progress

---

src/scripts/pagecontent.js
src/styles/_navigationbar.scss
src/styles/_pagecontent.scss

HFP-2596, HFP-2591 - visual changes

---

src/scripts/app.js
src/scripts/pagecontent.js
src/scripts/sidebar.js
src/scripts/statusbar.js
src/styles/main.scss

- Don't show menu on small surfaces by default
- Align items based on image in HFP-2587
- Use calculated radio instead of media queries

HFP-2587 - menu on mobile/small surface

---

src/styles/main.scss

Added scrolling to Apple devices when in fullscreen mode

HFP-2599 - scrolling on Apple devices

---

.babelrc
.eslintrc.json
library.json
package-lock.json
package.json
semantics.json
src/entries/main.js
src/scripts/app.js
src/scripts/pagecontent.js
src/scripts/sidebar.js
src/scripts/statusbar.js
src/scripts/summary.js
src/styles/_summary.scss
src/styles/main.scss
src/styles/style.scss
webpack.config.js

Semantics file are not updated with translations after talk with @icc . But all translations are grouped in the "sanitizeConfig"-function.

HFP-2708 Summary screen

---

src/scripts/sidebar.js
src/styles/_summary.scss

HFP-2708 design adjustments

---

language/fr.json

Translation fr

---

language/sv.json

New translation sv.json

---

src/scripts/summary.js

Use focus element instead of aria-live, since it conflicts with the
attempts control heading.

hfp-3437 announce submitted results

---

language/ca.json
language/fr.json
language/nl.json

Translations update from [Translate H5P](https://translate-h5p.tk/weblate/projects/h5p/h5p-interactive-book/)
for H5P/h5p-interactive-book.
Current translation status:

Translations update from Translate H5P

---

src/scripts/app.js
src/scripts/pagecontent.js
src/scripts/summary.js

HFP-3225 Implement review change requests

---

src/scripts/app.js
src/scripts/summary.js

- Compare two states to check the content is changed
- Reset the previous state on submit the answer
- Detect small changes in nested children content

JI-2969 IB prevent user to submit result over and over

---

src/scripts/sidebar.js

Reviewed and seem to works as intended. Ready for merge

JI-3302 Fix sublist items in navigation menu hidden on collapse

---

src/scripts/pagecontent.js

- Set default page value to first page

JI-4348 Fix IB content crash when exiting page is removed

---

src/scripts/cover.js
src/styles/_cover.scss

When merged in, will fix the visuals of Echo videos on the cover. Please note that this requires https://github.com/h5p/h5p-video/pull/122/commits/48ffca359486d1cecc42e9fa499f459a5563a92a as well.

HFP-3941 Fix echo video on cover

---

src/scripts/app.js

This is likely a temporary fix until https://h5ptechnology.atlassian.net/browse/LB-140 is fixed

LB-104 Show submit button despite row

---

src/scripts/app.js

JI-6555 H5P taking the focus on a Page in Canvas

---

language/ja.json

Create Japanese translations (ja.json) for Interactive Book

Create Japanese (ja.json) for Interactive Book

---

src/scripts/app.js

When merged in, will fix HFP-4265 and hopefully the infinite resize loop in Brightspace, too.

VA-982 Prevent resize loop with core

---

src/styles/_navigationbar.scss

When merged in, will ensure the folder icon is used for the Summary&Submit button.

VA-991 Ensure folder icon for summary&submit button

---

src/styles/_statusbar.scss

When merged in, will fix the main title text overflowing the available space.

VA-917 Fix title text overflow

---

language/hu.json

add hungarian translation

---

package-lock.json
package.json
src/scripts/app.js
src/scripts/colors.js
src/styles/_navigationbar.scss

- **VA-871 remove old color before redesign**
- **VA-871 add tinycolor**
- **VA-871 reuse logic from h5pcom**

VA-871 make base color work with the new theme
